Update build.yml

diff --git a/.github/workflows/build.yml b/.github/workflows/build.yml
--- a/.github/workflows/build.yml
+++ b/.github/workflows/build.yml
@@ -37,37 +37,57 @@ jobs:
           #- recipe-wayfire.yml
     steps:
       - name: Checkout repo
-        uses: actions/checkout@v4
+        #uses: actions/checkout@v4
+        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2
 
-      - name: Add yq (for reading recipe.yml)
-        uses: mikefarah/yq@v4.44.3
+      #- name: Add yq (for reading recipe.yml)
+      #  uses: mikefarah/yq@v4.44.3
+
+      #- name: Gather image data from recipe
+      #  run: |
+          #echo "IMAGE_NAME=$(yq '.name' ./recipes/${{ matrix.recipe }})" >> $GITHUB_ENV
+          #echo "IMAGE_MAJOR_VERSION=$(yq '.image-version' ./recipes/${{ matrix.recipe }})" >> $GITHUB_ENV
+          #BASE_IMAGE=$(yq '.base-image' ./recipes/${{ matrix.recipe }})
+          #echo "BASE_IMAGE_NAME=$(echo $BASE_IMAGE | sed 's/.*\/.*\///')" >> $GITHUB_ENV
 
       - name: Gather image data from recipe
         run: |
-          echo "IMAGE_NAME=$(yq '.name' ./recipes/${{ matrix.recipe }})" >> $GITHUB_ENV
-          echo "IMAGE_MAJOR_VERSION=$(yq '.image-version' ./recipes/${{ matrix.recipe }})" >> $GITHUB_ENV
-          BASE_IMAGE=$(yq '.base-image' ./recipes/${{ matrix.recipe }})
+          echo "IMAGE_NAME=$(grep '^name:' ./recipes/${{ matrix.recipe }} | sed 's/^name: //')" >> $GITHUB_ENV
+          echo "IMAGE_MAJOR_VERSION=$(grep '^image-version:' ./recipes/${{ matrix.recipe }} | sed 's/^image-version: //')" >> $GITHUB_ENV
+          BASE_IMAGE=$(grep '^base-image:' ./recipes/${{ matrix.recipe }} | sed 's/^base-image: //')
           echo "BASE_IMAGE_NAME=$(echo $BASE_IMAGE | sed 's/.*\/.*\///')" >> $GITHUB_ENV
 
+      #- name: Validate kernel and kmod versions
+      #  uses: Wandalen/wretry.action@v3.7.3
+      #  with:
+      #    attempt_limit: 3
+      #    attempt_delay: 15000
+      #    command: |
+      #      set -eo pipefail
+      #      linux=$(skopeo inspect docker://ghcr.io/ublue-os/main-kernel:41 | jq -r '.Labels["ostree.linux"]')
+      #      AKMODS_KERNEL_VERSION=$(skopeo inspect docker://ghcr.io/ublue-os/akmods:main-41 | jq -r '.Labels["ostree.linux"]')
+      #      if [[ "${linux}" != "${AKMODS_KERNEL_VERSION}" ]]; then
+      #        echo "Kernel Versions do not match between AKMODS and Cached-Kernel."
+      #        exit 1
+      #      fi
+      #      echo "KERNEL_VERSION=$linux" >> $GITHUB_ENV
+
       - name: Validate kernel and kmod versions
-        uses: Wandalen/wretry.action@v3.7.3
-        with:
-          attempt_limit: 3
-          attempt_delay: 15000
-          command: |
-            set -eo pipefail
-            linux=$(skopeo inspect docker://ghcr.io/ublue-os/main-kernel:41 | jq -r '.Labels["ostree.linux"]')
-            AKMODS_KERNEL_VERSION=$(skopeo inspect docker://ghcr.io/ublue-os/akmods:main-41 | jq -r '.Labels["ostree.linux"]')
-            if [[ "${linux}" != "${AKMODS_KERNEL_VERSION}" ]]; then
-              echo "Kernel Versions do not match between AKMODS and Cached-Kernel."
-              exit 1
-            fi
-            echo "KERNEL_VERSION=$linux" >> $GITHUB_ENV
+        run: |
+          set -eo pipefail
+          linux=$(skopeo inspect docker://ghcr.io/ublue-os/main-kernel:41 | jq -r '.Labels["ostree.linux"]')
+          AKMODS_KERNEL_VERSION=$(skopeo inspect docker://ghcr.io/ublue-os/akmods:main-41 | jq -r '.Labels["ostree.linux"]')
+          if [[ "${linux}" != "${AKMODS_KERNEL_VERSION}" ]]; then
+            echo "Kernel Versions do not match between AKMODS and Cached-Kernel."
+            exit 1
+          fi
+          echo "KERNEL_VERSION=$linux" >> $GITHUB_ENV
 
       - name: Build toxicblue
-        uses: blue-build/github-action@v1.6.2
+        #uses: blue-build/github-action@v1.6.2
+        uses: blue-build/github-action@4d8b4df657ec923574611eec6fd7e959416c47f0 # v1.8.1
         with:
-          cli_version: v0.8.20
+          cli_version: v0.9.0
           recipe: ${{ matrix.recipe }}
           cosign_private_key: ${{ secrets.SIGNING_SECRET }}
           registry_token: ${{ github.token }}
@@ -75,3 +95,5 @@ jobs:
 
           # включено по умолчанию, отключите, если ваше изображение маленькое и вы хотите получить более быструю сборку     
           maximize_build_space: true
+          
+          squash: true
